дз готово
IlyaKaput/legendary-parakeet pull request #1
Opened 2023-09-11 14:29 UTC by IlyaKaput

2023-09-11 18:04 UTC, KozlovAV426 requested changes

2023-09-11 18:04 UTC, KozlovAV426 commented on untitled/src/Homework1.java
> +        if(x>=y&&x>=z){
добавить пробелы x >= y && x >= z
везде поправить

2023-09-11 18:04 UTC, KozlovAV426 commented on untitled/src/Homework1.java
> +        return 0;
функция должна возвращать максимум, почему возвращаем 0?))
нужно не выводить в консоль, а вернуть максимум

2023-09-11 18:04 UTC, KozlovAV426 commented on untitled/src/Homework1.java
> +            int m = n*fact(n-1);
пробелы

2023-09-11 18:04 UTC, KozlovAV426 commented on untitled/src/Homework1.java
> +            return m;
зачем присваивать переменную и сразу ее возвращать, тогда уж сразу return n.multiply(fact(n.subtract(BigInteger.valueOf(1))));
Для единички уже есть константа BigInteger.ONE

2023-09-11 18:04 UTC, KozlovAV426 commented on untitled/src/Homework1.java
> +            res[i] = arr[l-i-1];
пробелы

2023-09-11 18:04 UTC, KozlovAV426 commented on untitled/src/Homework1.java
> +        while(t){
t - не самое лучшее название для переменной)
пробелы -> while (t) {
}

2023-09-11 18:05 UTC, KozlovAV426 commented
Плюс, хорошо было бы удалить все лишние файлы (.idea, .iml), в репе оставлять только код

2023-09-14 11:26 UTC, IlyaKaput commented on untitled/src/Homework1.java
> +        return 0;
Ок, просто поменять println на return

2023-09-14 15:18 UTC, closed without merging