Homework 2
IlyaKaput/legendary-parakeet pull request #3
Opened 2023-09-25 11:15 UTC by IlyaKaput

2023-10-16 14:22 UTC, KozlovAV426 requested changes

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/IntHolder.java
> +    public IntHolder(int n){
пробелы добавить - IntHolder(int n){ -> IntHolder(int n) {

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/IntHolder.java
> +        int a = n.getInt();
внутри метода класса имеется доступ к приватным полям, так что можно без сеттера

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Task1.java
> +           if(str.substring(i, i+m).equals(oldStr)){
здесь добавить пробелы

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Task1.java
> +               i += newStr.length()-1;
тут тоже пробелы

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Task1.java
> +       return str;
можно было воспользоваться replace методом

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Point.java
> +public class Point {
final class для иммутабельности

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Point.java
> +    private double y;
final поля для иммутабельности

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Point.java
> +    public void setX(double x){
убрать сеттеры для неизменяемости

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Point.java
> +    public void translate(double x, double y){
так как класс неизменяемый translate возвращает новую точку с новыми координатами, старую не меняет

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Point.java
> +        this.x *= a;
аналогично translate

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Pyramid.java
> +        this.setVolume(area*height/3);
пробелы area * height / 3

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Pyramid.java
> +        this.setVolume(area*height/3);
а без this нельзя вызвать setVolume?

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Ball.java
> +        this.setVolume(radius*radius*4/3*3.14159265);
пробелы

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Car.java
> +    private int maxFuel=0;
пробелы

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Cat.java
> +        this.age= age;
форматирование

2023-10-16 14:22 UTC, KozlovAV426 commented on hw2/src/Contact.java
> +        if(!email.substring(email.length()-10).equals("@gmail.com")){
10 вынессти в константу + форматирование

2023-10-16 14:51 UTC, IlyaKaput commented on hw2/src/Pyramid.java
> +        this.setVolume(area*height/3);
Можно, судя по самому существованию этого вопроса. Но не упростит ли это понимание кода? Я в принципе старался везде, где можно писать с this

2023-10-16 14:54 UTC, merged

2023-10-16 15:01 UTC, KozlovAV426 commented
а зачем ты смерджил пр, если я не просмотрел твои изменения еще? Мерджу только я в конце, когда все сделано))

2023-10-16 15:08 UTC, IlyaKaput commented
Вот те три слова, которые подчеркивает красным автокоррект я тоже не понимаю, у меня опыта с Гитхабом секунд пять, я просто починил то, что мне прилетело на мейл
С уважением, 
Илья Капуткин
 
 
  
>Понедельник, 16 октября 2023, 18:01 +03:00 от KozlovAV426 ***@***.***>:
> 
> 
>а зачем ты смерджил пр, если я не просмотрел твои изменения еще? Мерджу только я в конце, когда все сделано))
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you modified the open/close state. Message ID:  <IlyaKaput/legendary-parakeet/pull/3/c1764679047 @ github . com>
 

2023-10-16 15:18 UTC, KozlovAV426 commented
> Вот те три слова, которые подчеркивает красным автокоррект я тоже не понимаю, у меня опыта с Гитхабом секунд пять, я просто починил то, что мне прилетело на мейл С уважением,  Илья Капуткин      
> Понедельник, 16 октября 2023, 18:01 +03:00 от KozlovAV426 ***@***.***>:     а зачем ты смерджил пр, если я не просмотрел твои изменения еще? Мерджу только я в конце, когда все сделано)) — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you modified the open/close state. Message ID: <IlyaKaput/legendary-parakeet/pull/3/c1764679047 @ github . com>

я не совсем понял, что значит "вот те три слова"

2023-10-16 19:39 UTC, IlyaKaput commented
«смерджил», «пр», «мерджу». Я чисто из словообразования русского языка понимаю, что первое — совершенный вид прошедшего времени от глагола «мерджить», а третье — первое лицо, настоящее время от того же глагола, но значения его я не знаю
 
 
С уважением, 
Илья Капуткин
 
 
  
>Понедельник, 16 октября 2023, 18:18 +03:00 от KozlovAV426 ***@***.***>:
> 
> 
>Вот те три слова, которые подчеркивает красным автокоррект я тоже не понимаю, у меня опыта с Гитхабом секунд пять, я просто починил то, что мне прилетело на мейл С уважением,  Илья Капуткин      
>Понедельник, 16 октября 2023, 18:01 +03:00 от KozlovAV426  @ .***>:     а зачем ты смерджил пр, если я не просмотрел твои изменения еще? Мерджу только я в конце, когда все сделано)) — Reply to this email directly, view it on GitHub , or unsubscribe . You are receiving this because you modified the open/close state. Message ID: < /pull/3 /c1764679047 @ github . com>
я не совсем понял, что значит "вот те три слова"
—
Reply to this email directly,  view it on GitHub , or  unsubscribe .
You are receiving this because you modified the open/close state. Message ID:  <IlyaKaput/legendary-parakeet/pull/3/c1764723531 @ github . com>
 

2023-10-28 13:52 UTC, ASemenovng commented on hw2/src/Car.java
> +    public static class Builder {
тест